Prevent transactions being returned when they are not supposed to
cuenca-mx/speid pull request #377
Opened 2022-10-20 16:21 UTC by chiqeen03

- Transactions can only be marked as failed when they are from the current active day.
- Transactions are checked with STP before being marked as failed.

2022-10-20 17:26 UTC, pachCode commented on .python-version
> +3.8.11
agregar a gitignore

2022-10-20 17:26 UTC, pachCode commented on Makefile
> +PYTHON = python3
por qué se cambió?

2022-10-20 17:28 UTC, pachCode commented on speid/models/transaction.py
> +            return estado
puedes hacer if clave_rastreo y así evitas el return a media función

2022-10-20 17:29 UTC, pachCode commented on speid/models/transaction.py
> +                raise
que error lanzaría?

2022-10-20 17:30 UTC, pachCode commented on speid/tasks/orders.py
> +        estado = transaction.check_stp_status()
Si lanzas un rais en la función check_stp_status y aquí no hay un try va a tronar y como es una tarea posiblemente se esté reinntentando

2022-10-20 17:30 UTC, pachCode commented on speid/utils.py
> +BEGIN_HOLY_WEEK = os.getenv('BEGIN_HOLY_WEEK', '2023-04-06')
Esto va a cambiar en dos años, hay forma de que sea más tiempo?

2022-10-20 17:41 UTC, chiqeen03 commented on Makefile
> +PYTHON = python3
lo moví para mi local, y olvidé regresarlo

2022-10-20 17:43 UTC, chiqeen03 commented on speid/models/transaction.py
> +                raise
el `StpmexException` de arriba. Como está en el except, si no es el error esperado solo lo propaga. Sería si se desconfiguran las llaves o algo similar

2022-10-20 17:44 UTC, chiqeen03 commented on speid/tasks/orders.py
> +        estado = transaction.check_stp_status()
agrego except y capture_exception

2022-10-21 17:25 UTC, felipaoo requested changes

2022-10-21 17:25 UTC, felipaoo commented on speid/tasks/orders.py
> +        assert get_next_business_day(transaction.created_at) == date.today()
el cambio de día hábil es 6 pm hora local. `date.today()` retorna la zona horaria configurada en el server debemos tener cuidado porque puede que cuando haya cambio de día el server tenga otra hora y `get_next_business_day` retorne otra

2022-10-21 17:25 UTC, felipaoo commented on speid/utils.py
> +def get_next_business_day(fecha: dt.date) -> dt.date:
parece que esto es código repetido. tal vez esta en stpmex

2022-10-21 17:25 UTC, felipaoo commented on tests/conftest.py
> +        yield queue_mock
para que se hace `yield`?

2022-10-21 17:25 UTC, felipaoo commented on tests/tasks/test_orders.py
> +    order = dict(
es posible reutilizar el fixture de orden?

2022-10-21 17:42 UTC, felipaoo commented on speid/tasks/orders.py
> +        try:
No creo que sea necesario revisar en STP para todas estas excepciones. Muchas de ellas indican que STP rechazó y no está en su sistema por lo que pueden ser retornadas con seguridad.

Según veo solo `AssertionError` serían candidatas a este paso.

2022-10-21 17:46 UTC, felipaoo commented on speid/models/transaction.py
> +    def check_stp_status(self) -> Optional[STPEstado]:
sugiero renombrar a `fetch_stp_status`

2022-10-21 17:47 UTC, felipaoo commented on speid/models/transaction.py
> +        if self.clave_rastreo:
para qué es este `if`. Todos los transactions deben tener `clave_rastreo`

2022-10-24 15:52 UTC, chiqeen03 commented on tests/conftest.py
> +        yield queue_mock
lo había metido paara evaluar que fuera llamado con `assert_called_once`, etc. pero aal final no lo utilicé. Lo quito

2022-10-27 22:31 UTC, chiqeen03 commented on speid/models/transaction.py
> +                    raise
https://github.com/cuenca-mx/stpmex-python/pull/270

2022-10-31 20:15 UTC, felipaoo requested changes

2022-10-31 20:15 UTC, felipaoo commented on speid/tasks/orders.py
> +            get_next_business_day(transaction.created_at)
debes pasar como parámetro la fecha y hora de la zona horaria para cdmx (dependiendo de horario invierno/verano), también en STP.

2022-10-31 20:15 UTC, felipaoo commented on speid/utils.py
> +
borrar si ya no es necesario

2022-11-07 23:52 UTC, alexviquez requested changes
Tengo unas dudas respecto a lo que ocurre si:
- Falla stp en caso de superar la cuota de peticiones, parece que el código las marcaría failed de todas formas lo que esta mal, hay que revisar esa parte y el test

2022-11-07 23:52 UTC, alexviquez commented on speid/models/transaction.py
> +            ...
Parece que el endpoint de consulta tiene algunas limitantes, habría que revisar en caso de que se rebase el limite volver a intentar en un intervalo de 30 segundos

2022-11-07 23:52 UTC, alexviquez commented on speid/models/transaction.py
> +            ...
El intervalo fue extraido de la documentación

2022-11-07 23:52 UTC, alexviquez commented on speid/tasks/orders.py
> +            if not estado or estado in [
creo que aquí siempre necestiarías que exista un estado para marcarla como fallida

2022-11-07 23:52 UTC, alexviquez commented on tests/tasks/test_orders.py
> +    assert transaction.estado is Estado.failed
si el estado no debería cambiar, debería estar en Error

2022-11-08 18:38 UTC, chiqeen03 commented on speid/tasks/orders.py
> +            if not estado or estado in [
no estoy seguro, hay transacciones que podrían no encontrarse en la api, y de igual manera se tendrían que psar como fallidas

2022-11-08 18:48 UTC, chiqeen03 commented on tests/tasks/test_orders.py
> +    assert transaction.estado is Estado.failed
ya corregí el comment

2022-11-08 23:08 UTC, alexviquez requested changes
solo una duda con un test

2022-11-08 23:08 UTC, alexviquez commented on tests/tasks/test_orders.py
> +    transaction.delete()
este test me genera issue, si la transacción esta en error, el tiempo esta fuera del delta de 2 horas y además no se encuentra en STP, porque retornarla?

2022-11-09 00:52 UTC, pachCode approved these changes

2022-11-09 16:07 UTC, merged